# Generated by Django 3.2.9 on 2021-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('url', models.URLField(verbose_name='Link on company page')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Company Address')),
                ('date_created', models.DateField(verbose_name='Foundation Date')),
                ('logo', models.FileField(upload_to='media/companies_logo')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-date_created'],
            },
        ),
    ]
