# Generated by Django 3.2.9 on 2021-11-08 21:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='UA', unique=True),
        ),
    ]
