# Generated by Django 3.2.9 on 2021-11-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='client', max_length=12, verbose_name='User Type'),
        ),
    ]
