# Generated by Django 3.2.9 on 2021-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'client'), ('admin', 'admin'), ('super_admin', 'super_admin')], default='client', max_length=12, verbose_name='User Type'),
        ),
    ]
